### PR TITLE
 GUI revision 

### PR DESCRIPTION
**Pull request by quaeritis**
Hi @SamSchott ,

I made a little bit on the GUI.
Can you see if you like it that way?

Kind regards
quaeritis

### CODE REVIEW

**Comment by samschott** [comment]
Hi @quaeritis,

I like the idea, thank you for the work! A few issues about functionality:

1. Spin boxes are neat, but they also limit the input. I can't input mV values anymore. Is there a way to enable that, without increasing the number of decimal points shown by default?

2. Can we make the minimum and maximum voltage adaptable to the Keithley value smuX.source.limitY instead of fixed -200V to 200V? This is a good idea in any case, even when retaining standard line edits.

3. I can only input integration times and settling times that are multiples of 1. We use mostly integration times < 0.1 sec per data point and the Keithley 2612b only accepts values from 0.001 to 25 PLC (power line cycles of 1/60Hz or 1/50Hz). For a 60Hz electricity supply, acceptable values are between 17 µsec to 0.4 sec. If we use a spin box, it should adapt over those orders of magnitude.

4. It may be a good idea to adapt input validators for the integration time, as specified above.

And a few gripes about the UI, even though I like the separation into group boxes:

1. The UI looks very busy now, at least on macOS. Maybe a few vertical and horizontal spacers would help?

2. Please keep the values aligned to the right. 

3. Is it just my imagination, or do the titles of the group boxes have different sizes? "Transfer measurement:" seems to have a larger font size than the others.

Sorry for all the nitpicking! 

Best,
Sam

screen shot 2018-10-22 at 19 28 35

**Comment by quaeritis** [comment]
@SamSchott
first of all thanks for the comments. I will revise that in the next few days and then go into more detail on the above points.

The difference in appearance is more extreme than I thought. That's what it looks like for me (just fix the label):
keithleygui

Regarding the spinBoxes I am not sure if I understood the mV problem but I can show additional decimal places if that is meant?

Maybe this is interesting too:
https://github.com/Ulm-IQO/qudi/blob/master/qtwidgets/scientific_spinbox.py

**Comment by samschott** [comment]
_Regarding the spin boxes:_

Yes, that is basically the problem. Many Keithleys can resolve voltage steps down to 5 µV. With Line Edits and a QDoubleValidator there is a lot of flexibility in entering voltages. For instance, you can enter "5e-6" in the voltage step field or "0.0000005" - both will be accepted. Strings that cannot be converted by float() will be rejected. That was my reason for choosing this approach.

When using a spin box, I get the impression that you need to always display the number of allowed decimal places. But there may be an elegant way around it. The Scientific SpinBox in your link may be solution, I will have a look.

Same holds for the integration time. Reasonable input values will vary between µsec and sec and being able to enter values in scientific notion makes things easier.

Regrading input validation, we should definitely query maximum and minimum allowed values from the Keithley upon connection and add them as ranges to the QDoubleValidator. 

There may also be a way to query and return error messages from the Keithley on a driver level (using errorqueue.next() ) when an invalid input is given.

_Regarding UI design:_

I would prefer larger margins around each group boxes, or maybe the use of horizontal lines instead of boxes to reduce clutter.

**Comment by samschott** [comment]
Inspired by your idea of using group boxes: [https://github.com/OE-FET/keithleygui/tree/gui_updates](https://github.com/OE-FET/keithleygui/tree/gui_updates). It may still have a few bugs.

I also added a new IV sweep tab, and made a few more settings accessible. Feel free to add spin boxes and proper input validators if you like. I actually really like the scientific_spinbox implementation from your link!

**Comment by quaeritis** [comment]
further GUI development  under: #9

**Pull request closed without merging**
