### PR TITLE
move address selection in the main GUI and add a visa library dialog

### PR DESCRIPTION
**Pull request by quaeritis**
Hi @SamSchott,

I got the address selection in the main GUI and added a search function. I also added a dialog to select the used VISA library (important for Windows).

needed: https://github.com/OE-FET/keithley2600/pull/5

Kind regards
quaeritis

### CODE REVIEW

**Comment by samschott** [comment]
Hi @quaeritis,

I like the search function and was planning to add an option for the visa backend myself. Thanks a lot for this! Would you be able to integrate both in a separate ConnectionDialog class?

There are a few advantages of a separate dialog class:

1. The functions to search for visa instruments, select an address, and select an interface are all related to the connection. Having them bundled simplifies the UI.

2. Following the above, the code can be reused for any instrument object with the methods 'visa_address', 'visa_library', 'connect', and 'disconnect'. In fact, we currently use the AddressDialog across all of our instrument UIs, and could then easily include your improvements.

3. These setting are accessed only occasionally, mostly when changing the Keithley or the PC. I see no need to clutter the main UI with this. 

What do you think?
Sam

**Comment by quaeritis** [comment]
Hi @quaeritis,

yes that's maybe a bit too much for the main GUI and you only need to configure it once. I think it would be great to see which device I connected / disconnected. Maybe there should be an address near the LED or something?

In addition, I was interested in whether list_resources () also TCP device finds (we work on GPIB)? Then I would change the code a bit.

I noticed today while testing the visa_library changes only after a restart take effect an idea why?

Will make the changes as soon as possible.

Kind regards
quaeritis

**Comment by samschott** [comment]
Yes, its a good idea to have a small label next to the LED. Currently there only is a brief message displayed in the status bar.

I don't know which resources are detected with list_resources() but ethernet devices consistently do not show up on our PC. Thats quite a shame, since we exclusively use ethernet.

The visa_library changes do not have any effect since the resource manager of the driver is loaded during **\_\_init\_\_()** and not during **connect()**. The only thing you currently do is change the config file and therefore the backend for future Keithley2600 instances. You would have to move **self.rm = visa.ResourceManager(self.visa_library)** to the **connect()** method and destroy it in the **disconnect()** method.

**Comment by samschott** [comment]
@quaeritis, I have moved loading the resource manager form **\_\_init\_\_()** to **connect()** in https://github.com/OE-FET/keithley2600/commit/37e46b0d7d182f62e1a1ad00947440867cb38d1b, among other code simplifications. Let me know if this still poses problems.

**Comment by quaeritis** [comment]
further development here #15

**Pull request closed without merging**
