### PR TITLE
add ConnectionDialog

### PR DESCRIPTION
**Pull request by quaeritis**
Add a connection dialog that allows to set visa_library and search for
addresses.

### CODE REVIEW

**Comment by samschott** [comment]
This looks good. A few suggested changes:

- I would not load the keithley address from the config file, but rather from self.keithley.visa_address. This way, the text field will always be populated with the current address.

- Switch to NI-VISA as default library in the config file. If this cannot be found PyVISA will automatically fall back to pyvisa-py. 

- It does not make sense to **rm.close()** in the disconnect method of the keithley: searching for visa instruments with **rm.list_resources()** will then fail after a disconnect. I therefore removed **rm.close()** and moved **rm.ResourceManager()** back to **\_\_init\_\_()**. You will have to manually **rm.close()**  and reopen after disconnecting the visa in the **_onAccept** callback.

- Should we include an "Automatically detect available visa library" checkbox? When checked, the manual selection could be grayed out. This seems a bit more self-explanatory than a black text field. We could still populate the textfield with '@py' if PyVISA selects pyvisa-py.

- Maybe add an **_onReject()** callback which discards any user input when Cancel is clicked?

**Comment by samschott** [comment]
Have a look at https://github.com/OE-FET/keithleygui/tree/SamSchott-patches, this should fix some of the above. I cannot figure out how to create a pull request to your ConnectionDialog branch.

**Comment by quaeritis** [comment]
It seems that an empty default value for VISA LIBRARY (in conf) is a problem.
I think there are different ways to solve this, what do you think?

**Comment by samschott** [comment]
Really? How so? It runs without issues here.

**Comment by quaeritis** [comment]
delete ~/.keithleygui excuse the bad explanation.
VISA LIBRARY then contains only an empty string.
Which is synonymous with: `rm = visa.ResourceManager('')`

**Comment by samschott** [comment]
Sorry, I still don't really understand. Why is it problem to have an empty string as default conf? This just triggers PyVisa to search for the NI-VISA visa library, and if unavailable, fall back to pyvisa-py (which is among the requirements of the driver). 

It may be confusing in the ConnectionDialog for the user to just see an empty field, therefore my suggestion of a checkbox labeled "Automatically detect available visa library", but the UI runs fine. **rm.list_resources()** still works.

**Comment by quaeritis** [comment]
I get the following at startup:
```
Traceback (most recent call last):
  File "/home/quaeritis/.local/bin/keithleygui", line 11, in <module>
    load_entry_point('keithleygui', 'gui_scripts', 'keithleygui')()
  File "/home/quaeritis/keithleygui/keithleygui/main.py", line 755, in run
    keithley = Keithley2600(KEITHLEY_ADDRESS, VISA_LIBRARY)
  File "/home/quaeritis/keithley2600/keithley2600/keithley_driver.py", line 393, in __init__
    Keithley2600Base.__init__(self, visa_address, visa_library)
  File "/home/quaeritis/keithley2600/keithley2600/keithley_driver.py", line 254, in __init__
    self.rm = visa.ResourceManager(self.visa_library)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1499, in __new__
    visa_library = open_visa_library(visa_library)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1471, in open_visa_library
    return cls(argument)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 97, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
```
Because I have no NI-VISA visa library on the dev machine.
```
>>> import visa
>>> rm = visa.ResourceManager('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1499, in __new__
    visa_library = open_visa_library(visa_library)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1471, in open_visa_library
    return cls(argument)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 97, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:

>>> rm = visa.ResourceManager()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1499, in __new__
    visa_library = open_visa_library(visa_library)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 1471, in open_visa_library
    return cls(argument)
  File "/home/quaeritis/.local/lib/python3.7/site-packages/PyVISA-1.9.0-py3.7.egg/pyvisa/highlevel.py", line 97, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
```
As you already said, it should be used as fallback pyvisa-py. Which is not the case right now.

**Comment by samschott** [comment]
Yeah, that does look like a problem. But I cannot reproduce it. Does the bare `rm = visa.ResourceManager()` or `rm = visa.ResourceManager('')` work for you after `import visa`? There should be no difference between the two since visa.ResourceManager takes `visa_library=''` as a default if no argument is given.

**Comment by samschott** [comment]
Sorry, didn't see your edit. What do you get when running `pyvisa-info` in the command line?

**Comment by quaeritis** [comment]
The problem is a bit strange. I am now at home on another computer without NI-VISA visa library and can not reproduce the problem. keithleygui starts easily.

If I have time I will tomorrow look what is output on the affected PC of pyvisa-info.

**Comment by quaeritis** [comment]
Output on the affected PC of pyvisa-info:
```
 $ pyvisa-info                   
Machine Details:
   Platform ID:    Linux-4.18.12-arch1-1-ARCH-x86_64-with-arch
   Processor:      

Python:
   Implementation: CPython
   Executable:     /usr/bin/python
   Version:        3.7.0
   Compiler:       GCC 8.2.1 20180831
   Bits:           64bit
   Build:          Sep 15 2018 19:13:07 (#default)
   Unicode:        UCS4

PyVISA Version: 1.9.0

Backends:
   ni:
      Version: 1.9.0 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.3.1
      ASRL INSTR:
         Please install PySerial (>=3.0) to use this resource type.
         No module named 'serial'
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      TCPIP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named 'gpib'

```

**Comment by samschott** [comment]
@quaeritis, the pyvisa-info output seems fine to me. I suspected it might be an issue with the version of pyvisa-py, but you are on the newest release.

From your traceback, it seems like PyVisa believes that NI-VISA should be installed but then cannot open the library. Was it installed on your system at some point by any chance?

Could you also get the debug output? It should be printed to the console when setting the root logging level to debug:

```
import logging
import sys

root = logging.getLogger()
root.setLevel(logging.DEBUG)

ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.DEBUG)
root.addHandler(ch)
```

**Comment by samschott** [comment]
Also, I split off the ConnectionDialog window into its own module, and refined the UI a little. 

See if you like it.

**Comment by quaeritis** [comment]
Yes, that looks great. The checkbox is really wonderfully comfortable.

**Comment by samschott** [comment]
As a reference, the debug on my PC says:

```
>>> rm = visa.ResourceManager()
No visa library specified, trying to find alternatives.
Environment variable PYVISA_LIBRARY is unset.
No user defined library files
Automatically found library files: []
Did not find NI binary
pyvisa-py is available.
Created ResourceManager with session 3466550
```

**Pull request merged**
