### PR TITLE
switch QlineEdit to ScienDSpinBox

### PR DESCRIPTION
**Pull request by quaeritis**
Hi @SamSchott,

I have changed the QlineEdits to ScienDSpinBoxs. The validators are not needed any more because ScienDSpinBoxs always returns fload. What is still missing are the range restrictions.

Kind regards
quaeritis

### CODE REVIEW

**Comment by samschott** [comment]
I like the spin boxes, they also simplify the main code. A few minor change requests:

- Could you have the content of all spin boxes aligned to the right (its a mixture between right and left at the moment)?

- Could you also use a fixed width for all spin boxes, maybe 70 pts?

- Finally, the spin boxes are currently named ScienDSpinBoxVgStart etc. Could you use lower case names of instances instead (scienDSpinBoxVgStart)? The upper cases in the middle are to keep consistent with PyQt, but at least the first letter should be lower case.

Thank you!
Sam

**Comment by quaeritis** [comment]
HI @SamSchott,

I made the changes.

1. fixed
2. I think 80 pts is better (probably still not enough)
3. Of course you're right about the widget names, that's so unpleasant.

Kind regards
quaeritis

**Comment by samschott** [comment]
Thanks!

**Comment by quaeritis** [comment]
@SamSchott:
sorry because of the ScienDSpinBoxs names I had to change that but then somehow it managed to reverse that, that comes from because I do not check the diff again :-(.

**Comment by samschott** [comment]
No worries, it was a quick search and replace!

**Pull request merged**
